name: "Build Kernel with Proton Clang"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "📥 Checkout Kernel Source (stable branch)"
        uses: actions/checkout@v4
        with:
          ref: stable

      - name: "🧰 Install Dependencies"
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev \
            libncurses-dev curl git wget lz4 cpio python3 python3-pip libarchive-tools \
            device-tree-compiler gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: "📦 Clone Proton Clang"
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git

      - name: "🛠️ Build Kernel"
        run: |
          export CLANG_PATH=$(pwd)/proton-clang
          export PATH="$CLANG_PATH/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CLANG_TRIPLE=aarch64-linux-gnu-

          # Use your existing defconfig
          make O=out ARCH=arm64 stock_defconfig

          # Compile kernel
          make -j$(nproc --all) \
            O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=$CROSS_COMPILE \
            CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 \
            CLANG_TRIPLE=$CLANG_TRIPLE

      - name: "📤 Upload Kernel Image"
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image
          path: |
            out/arch/arm64/boot/Image*
