name: "Build Kernel with Proton Clang"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "📥 Checkout Kernel Source"
        uses: actions/checkout@v4
      - name: "📥 Clone Kernel Source"
        run: |
         git clone --depth=1 --branch stable https://github.com/Ponleuz12/kernel_realme_sm4250.git

      - name: "🧰 Install Dependencies"
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev \
            libncurses-dev curl git wget lz4 cpio python3 python3-pip libarchive-tools \
            device-tree-compiler gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: "📦 Clone Proton Clang"
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git

      - name: "🛠️ Compile Kernel"
        run: |
          export CLANG_PATH=$(pwd)/proton-clang
          export PATH="$CLANG_PATH/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-

          # Clean and configure
          make O=out ARCH=arm64 menuconfig
          make O=out ARCH=arm64 savedefconfig
          cp out/defconfig arch/arm64/configs/RMX2195_defconfig
          git add arch/arm64/configs/RMX2195_defconfig
          git commit -m "Add RMX2195_defconfig"
          git push

          # Build with Clang
          make -j$(nproc --all) \
            O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            CLANG_TRIPLE=aarch64-linux-gnu-

      - name: "📤 Upload zImage or Image.gz"
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Output
          path: |
            out/arch/arm64/boot/Image*
