name: "Build Kernel with Proton Clang"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "📥 Checkout Kernel Source"
        uses: actions/checkout@v4

      - name: "📥 Clone Kernel Source"
        run: |
          git clone --depth=1 --branch stable https://github.com/Ponleuz12/kernel_realme_sm4250.git

      - name: "🧰 Install Dependencies"
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev \
            libncurses-dev curl git wget lz4 cpio python3 python3-pip libarchive-tools \
            device-tree-compiler gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: "📦 Clone Proton Clang"
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git

      - name: "🛠️ Compile Kernel"
        run: |
          cd kernel_realme_sm4250
          export CLANG_PATH=$(pwd)/../proton-clang
          export PATH="$CLANG_PATH/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CLANG_TRIPLE=aarch64-linux-gnu-

          echo "📂 Listing defconfigs..."
          ls arch/arm64/configs

          echo "⚙️ Running stock_deconfig"
          make O=out ARCH=arm64 stock_deconfig

          echo "🔨 Building kernel..."
          make -j$(nproc --all) \
            O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=$CROSS_COMPILE \
            CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 \
            CLANG_TRIPLE=$CLANG_TRIPLE

      - name: "📤 Upload Kernel Image"
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Output
          path: |
            kernel_realme_sm4250/out/arch/arm64/boot/Image*
